server:
  port: 8080

spring:
  datasource:
    username: root
    password: '!QAZ2wsx'
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://49.235.85.106:3304/zhuge?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8